/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Toko;

import javax.swing.table.DefaultTableModel;
import javax.xml.transform.Result;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author DBSS_050
 */
public class Form_supplier extends javax.swing.JFrame {

    /**
     * Creates new form Form_member
     */
    private DefaultTableModel model;
    public Form_supplier() throws SQLException {
        initComponents();
        showData();
        sort();
    }
    public DefaultTableModel saction() throws SQLException{
        DefaultTableModel tm = (DefaultTableModel) Tabel_supp.getModel();
        return tm;
    }
    
    private void sort() throws SQLException{
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(saction());
        Tabel_supp.setRowSorter(sorter);
    }
    public void showData(){
        Object header[]={"Id_supplier","Nama","Id_produk","No_telepon","Alamat"};
        model = new DefaultTableModel(null , header);
        Tabel_supp.setModel(model);
        model.setRowCount(0);
        Koneksi.Konek();
        if (Koneksi.conn != null) {
            StatusKoneksi.setText("Koneksi Sukses");
        }else{
            StatusKoneksi.setText("Koneksi Gagal");
        }
        try {
        Statement stmt = Koneksi.conn.createStatement();
        String query = "SELECT * FROM Supplier";
        ResultSet rs = stmt.executeQuery(query);
        Object [] n = new Object[5];
            while (rs.next()) {
                n[0] = rs.getString("Id_supplier");
                n[1]  = rs.getString("Nama");
                n[2] = rs.getString("Id_produk");
                n[3]  = rs.getString("No_telepon");
                n[4]  = rs.getString("Alamat");
                model.addRow(n);
            }
        } catch (SQLException e ) {
            StatusKoneksi.setText("Gagal query");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_supp = new javax.swing.JTable();
        NamaLBL = new javax.swing.JLabel();
        NamaTF = new javax.swing.JTextField();
        IdprodTF = new javax.swing.JTextField();
        No_telepon = new javax.swing.JTextField();
        AlamatTF = new javax.swing.JTextField();
        Id_prod = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InsertQuery = new javax.swing.JButton();
        UpdateQuery = new javax.swing.JButton();
        DeleteQuery = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Tutup = new javax.swing.JButton();
        StatusKoneksi = new javax.swing.JLabel();
        BatalQuery = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Id_suppLBL = new javax.swing.JLabel();
        Id_suppTF = new javax.swing.JTextField();
        SearchId = new javax.swing.JButton();
        SearchNama = new javax.swing.JButton();
        SearchIdProd = new javax.swing.JButton();
        SearchNoTelp = new javax.swing.JButton();
        SearchAlamat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Tabel_supp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabel_supp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id_supplier", "Nama", "Id_produk", "No_telepon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabel_supp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_suppMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_supp);

        NamaLBL.setText("Nama");

        Id_prod.setText("Id_prod");

        jLabel3.setText("No_telepon");

        jLabel4.setText("Alamat");

        InsertQuery.setText("INSERT");
        InsertQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertQueryActionPerformed(evt);
            }
        });

        UpdateQuery.setText("UPDATE");
        UpdateQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateQueryActionPerformed(evt);
            }
        });

        DeleteQuery.setText("DELETE");
        DeleteQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteQueryActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FORM SUPPLIER");

        Home.setText("HOME");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Tutup.setText("TUTUP");
        Tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutupActionPerformed(evt);
            }
        });

        StatusKoneksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StatusKoneksi.setText("STATUS KONEKSI");

        BatalQuery.setText("BATAL");
        BatalQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalQueryActionPerformed(evt);
            }
        });

        Refresh.setText("REFRESH");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        Id_suppLBL.setText("Id_supp");

        SearchId.setText("Search");
        SearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIdActionPerformed(evt);
            }
        });

        SearchNama.setText("Search");
        SearchNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchNamaActionPerformed(evt);
            }
        });

        SearchIdProd.setText("Search");
        SearchIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIdProdActionPerformed(evt);
            }
        });

        SearchNoTelp.setText("Search");
        SearchNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchNoTelpActionPerformed(evt);
            }
        });

        SearchAlamat.setText("Search");
        SearchAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchAlamatActionPerformed(evt);
            }
        });

        jMenu1.setText("PENDATAAN");

        jMenuItem1.setText("Data Produk");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Data Member");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Data Supplier");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSAKSI");

        jMenuItem4.setText("Penjualan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Pembelian");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Home)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StatusKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(InsertQuery)
                                        .addComponent(DeleteQuery))
                                    .addComponent(jLabel4)
                                    .addComponent(Id_prod)
                                    .addComponent(jLabel3)
                                    .addComponent(NamaLBL)
                                    .addComponent(Id_suppLBL))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Id_suppTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(No_telepon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdprodTF)
                                    .addComponent(NamaTF)
                                    .addComponent(AlamatTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(BatalQuery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(UpdateQuery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchIdProd)
                                    .addComponent(SearchNama)
                                    .addComponent(SearchNoTelp)
                                    .addComponent(SearchAlamat)
                                    .addComponent(SearchId))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(249, 249, 249)
                        .addComponent(Refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tutup))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Home)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Tutup)
                                                .addComponent(Refresh)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 82, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Id_suppTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Id_suppLBL)
                                            .addComponent(SearchId))
                                        .addGap(47, 47, 47)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IdprodTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SearchIdProd)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NamaLBL)
                                    .addComponent(NamaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SearchNama))
                                .addGap(18, 18, 18)
                                .addComponent(Id_prod)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(No_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(SearchNoTelp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(SearchAlamat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsertQuery)
                            .addComponent(UpdateQuery))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BatalQuery)
                            .addComponent(DeleteQuery))
                        .addGap(18, 18, 18)
                        .addComponent(StatusKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Form_Home_Toko hom = new Form_Home_Toko();
        hom.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutupActionPerformed
        dispose();
        try {
            Koneksi.Tutup();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Home_Toko.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TutupActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            Form_produk prd = new Form_produk();
            prd.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            Form_supplier mbr = new Form_supplier();
            mbr.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            Form_supplier supp = new Form_supplier();
            supp.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Form_penjualan p = new Form_penjualan();
            p.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            Form_pembelian p = new Form_pembelian();
            p.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void Tabel_suppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_suppMouseClicked
        int baris = Tabel_supp.getSelectedRow();
        Id_suppTF.setText(Tabel_supp.getValueAt(baris, 0).toString());
        NamaTF.setText( Tabel_supp.getValueAt(baris, 1).toString());
        IdprodTF.setText(Tabel_supp.getValueAt(baris, 2).toString());
        No_telepon.setText(Tabel_supp.getValueAt(baris, 3).toString());
        AlamatTF.setText(Tabel_supp.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_Tabel_suppMouseClicked

    private void InsertQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertQueryActionPerformed
        try {
        Koneksi.Konek();
        String Query_T = "Insert Into Supplier values (?,?,?,?,?)";
            PreparedStatement ps = Koneksi.conn.prepareStatement(Query_T);
            ps.setString(1,Id_suppTF.getText());
            ps.setString(2,NamaTF.getText());
            ps.setString(3,IdprodTF.getText());
            ps.setString(4,No_telepon.getText());
            ps.setString(5,AlamatTF.getText());
            ps.executeUpdate();
            DefaultTableModel tM = (DefaultTableModel) Tabel_supp.getModel();
            JOptionPane.showMessageDialog(null,"Insert Succsessfully");   
            Refresh();
        } catch (SQLException e ) {
            JOptionPane.showMessageDialog(null,"Insert Fail");
        }
    }//GEN-LAST:event_InsertQueryActionPerformed

    private void UpdateQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateQueryActionPerformed
        try {
            String Id_supp = Id_suppTF.getText();
            Koneksi.Konek();
            String Query_T = "Update Supplier set Id_supplier = ?,Nama = ?,Id_produk = ?,No_telepon=?,Alamat=? where Id_supplier = ?;";   
            PreparedStatement ps = Koneksi.conn.prepareStatement(Query_T);
            ps.setString(1,Id_suppTF.getText());
            ps.setString(2,NamaTF.getText());
            ps.setString(3,IdprodTF.getText());
            ps.setString(4,No_telepon.getText());
            ps.setString(5,AlamatTF.getText());
            ps.setString(6,Id_supp);
            ps.executeUpdate();
            DefaultTableModel tM = (DefaultTableModel) Tabel_supp.getModel();
            JOptionPane.showMessageDialog(null,"Update Succsessfully");
            Refresh();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Update Failed\n Eror : "+ex);
        }
    }//GEN-LAST:event_UpdateQueryActionPerformed

    private void BatalQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalQueryActionPerformed
        setBatal();
    }//GEN-LAST:event_BatalQueryActionPerformed
    public void setBatal(){
        NamaTF.setText("");
        Id_suppTF.setText("");
        IdprodTF.setText("");
        No_telepon.setText("");
        AlamatTF.setText("");
    }
    private void DeleteQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteQueryActionPerformed
        String query = "DELETE FROM Supplier WHERE Id_supplier = '" + Id_suppTF.getText() +"';";
        try {
            PreparedStatement stmt = Koneksi.conn.prepareStatement(query);
            if (stmt.execute()) {
                JOptionPane.showMessageDialog(null,"Delete Failed");
            }else{
                JOptionPane.showMessageDialog(null,"Delete Success");
                Refresh();
            }
        } catch (SQLException e ) {
            JOptionPane.showMessageDialog(null,"Delete Failed\n Eror : "+e);
        }
    }//GEN-LAST:event_DeleteQueryActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        Refresh();
    }//GEN-LAST:event_RefreshActionPerformed
    public void Refresh(){
        try {
            dispose();
            Form_supplier m = new Form_supplier();
            m.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    private void SearchNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchNamaActionPerformed
        showSearchData("Nama", NamaTF.getText());
    }//GEN-LAST:event_SearchNamaActionPerformed

    private void SearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIdActionPerformed
        showSearchData("Id_supplier", Id_suppTF.getText());
    }//GEN-LAST:event_SearchIdActionPerformed

    private void SearchIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIdProdActionPerformed
        showSearchData("Id_produk", IdprodTF.getText());
    }//GEN-LAST:event_SearchIdProdActionPerformed

    private void SearchNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchNoTelpActionPerformed
        showSearchData("No_telepon", No_telepon.getText());
    }//GEN-LAST:event_SearchNoTelpActionPerformed

    private void SearchAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchAlamatActionPerformed
        showSearchData("Alamat", AlamatTF.getText());
    }//GEN-LAST:event_SearchAlamatActionPerformed
    public void showSearchData(String kolom , String param){
        try {
            model.setRowCount(0);
            Statement stmt = Koneksi.conn.createStatement();
            String query = "SELECT * FROM Supplier WHERE "+ kolom+"='"+param+"';";
            ResultSet rs = stmt.executeQuery(query);
            Object [] n = new Object[5];
            while (rs.next()) {
                n[0] = rs.getString("Id_supplier");
                n[1]  = rs.getString("Nama");
                n[2] = rs.getString("Id_produk");
                n[3]  = rs.getString("No_telepon");
                n[4]  = rs.getString("Alamat");
                model.addRow(n);
            }        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
        }    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_supplier().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Form_supplier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatTF;
    private javax.swing.JButton BatalQuery;
    private javax.swing.JButton DeleteQuery;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Id_prod;
    private javax.swing.JLabel Id_suppLBL;
    private javax.swing.JTextField Id_suppTF;
    private javax.swing.JTextField IdprodTF;
    private javax.swing.JButton InsertQuery;
    private javax.swing.JLabel NamaLBL;
    private javax.swing.JTextField NamaTF;
    private javax.swing.JTextField No_telepon;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton SearchAlamat;
    private javax.swing.JButton SearchId;
    private javax.swing.JButton SearchIdProd;
    private javax.swing.JButton SearchNama;
    private javax.swing.JButton SearchNoTelp;
    private javax.swing.JLabel StatusKoneksi;
    private javax.swing.JTable Tabel_supp;
    private javax.swing.JButton Tutup;
    private javax.swing.JButton UpdateQuery;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
